version: '3.3'
services:
  app:
    image: app-image:latest
    networks:
      - cloud
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=17031703"
      - "DB_HOST=db"
      - "DB_PORT=5432"

  db:
    image: postgres:latest
    networks:
      - cloud
    ports:
    - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=17031703
      - POSTGRES_USER=postgres
      - POSTGRES_DB=animsemestrwork
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
    external: true

networks:
  cloud:
    driver: bridge
