###

GET http://localhost:8080/authors/get
Accept: application/json

{
  "authorDtoList": [
    {
      "id": 1,
      "name": "Мунэюки Канэсиро",
      "info": "Мунэюки Канэсиро - японский художник манги. Он дебютировал в 2011 году в фильме \"По воле богов\", который был экранизирован. В 2018 году он выпустил \"Синий замок\" с Юсуке Номурой, который получил 45-ю премию \"Коданша Манга\" в категории \"сенэн\"."
    },
    {
      "id": 2,
      "name": "Тацуя Эндо",
      "info": "Тацуя Эндо - японский художник манги. Эндо наиболее известен по созданию манги Tista, Gekka Bijin и Spy × Family, а также других работ. Последняя работа в журнале Shonen Jump+ достигла рубежа в 10 миллионов физических и цифровых копий."
    },
    {
      "id": 5,
      "name": "Тайте Кубо",
      "info": "Тайте Кубо - японский мангака. Он наиболее известен своей мангой «Блич». Часто встречаются ошибочные варианты написания его псевдонима, например: Титэ Кубо, Кубо Тайт, Куботайт, Куботайто, Куботитэ."
    },
    {
      "id": 9,
      "name": "Test",
      "info": "Testtt info"
    },
    {
      "id": 3,
      "name": "CD Projekt Red",
      "info": "CD Projekt RED — компания-разработчик компьютерных игр, расположенная в Польше. Является дочерним предприятием компании CD Projekt."
    },
    {
      "id": 4,
      "name": "One",
      "info": "One - псевдоним японского мангаки, ставшего известным из-за перерисованной версии своей веб-манги «Ванпанчмен». ONE публикует  «Моб Психо 100» в онлайн-версии Weekly Shonen Sunday."
    },
    {
      "id": 6,
      "name": "Тацуки Фудзимото",
      "info": "Тацуки Фудзимото - японский мангака, наиболее известный своими работами Fire Punch и «Человек-бензопила». Окончил среднюю школу Никахо префектуры Акита и университет искусств и дизайна Тохоку, учился на факультете изящных искусств."
    }
  ]
}

###

GET http://localhost:8080/authors/get/filter
Accept: application/json

{
  "authorDtoList": [
    {
      "id": 1,
      "name": "Мунэюки Канэсиро",
      "info": "Мунэюки Канэсиро - японский художник манги. Он дебютировал в 2011 году в фильме \"По воле богов\", который был экранизирован. В 2018 году он выпустил \"Синий замок\" с Юсуке Номурой, который получил 45-ю премию \"Коданша Манга\" в категории \"сенэн\"."
    },
    {
      "id": 2,
      "name": "Тацуя Эндо",
      "info": "Тацуя Эндо - японский художник манги. Эндо наиболее известен по созданию манги Tista, Gekka Bijin и Spy × Family, а также других работ. Последняя работа в журнале Shonen Jump+ достигла рубежа в 10 миллионов физических и цифровых копий."
    },
    {
      "id": 5,
      "name": "Тайте Кубо",
      "info": "Тайте Кубо - японский мангака. Он наиболее известен своей мангой «Блич». Часто встречаются ошибочные варианты написания его псевдонима, например: Титэ Кубо, Кубо Тайт, Куботайт, Куботайто, Куботитэ."
    },
    {
      "id": 9,
      "name": "Test",
      "info": "Testtt info"
    },
    {
      "id": 4,
      "name": "One",
      "info": "One - псевдоним японского мангаки, ставшего известным из-за перерисованной версии своей веб-манги «Ванпанчмен». ONE публикует  «Моб Психо 100» в онлайн-версии Weekly Shonen Sunday."
    },
    {
      "id": 3,
      "name": "CD Projekt Red",
      "info": "CD Projekt RED — компания-разработчик компьютерных игр, расположенная в Польше. Является дочерним предприятием компании CD Projekt."
    },
    {
      "id": 6,
      "name": "Тацуки Фудзимото",
      "info": "Тацуки Фудзимото - японский мангака, наиболее известный своими работами Fire Punch и «Человек-бензопила». Окончил среднюю школу Никахо префектуры Акита и университет искусств и дизайна Тохоку, учился на факультете изящных искусств."
    }
  ]
}
###

POST http://localhost:8080/authors/post?name=MyTestAuthor&info=MyTestAuthor
Accept: application/json

{
  "id": 14,
  "name": "MyTestAuthor",
  "info": "MyTestAuthor"
}
###

PATCH http://localhost:8080/authors/patch?id=14&info=MyAuthor
Accept: application/json

{
  "id": 14,
  "name": "MyTestAuthor",
  "info": "MyAuthor"
}
###

DELETE http://localhost:8080/authors/delete?id=14
Accept: application/json

{
  "id": 14,
  "name": "MyTestAuthor",
  "info": "MyAuthor"
}